### ISSUE TITLE
Document Command Line Interface

### ISSUE THREAD

**Issue by ryankurte** [ryankurte/rust-esp32-wasm#1]
The CLI functions should be documented for newcomers (and forgetful people like me), currently the only information is the [source code](https://github.com/ryankurte/rust-esp32-wasm/tree/master/base/main) in the respective `XX_MGR_register_commands` functions.

## Tasks:

- [ ] FileSystem (`fs`) functions
- [ ] Task (`task`) functions
- [ ] Wifi (`wifi`) functions

**Comment by ryankurte** [comment]
Mitigated via `help` implementation
