### ISSUE TITLE
Support task logging

### ISSUE THREAD

**Issue by ryankurte** [ryankurte/rust-esp32-wasm#10]
- For development it'd be super neat to be able to throw a task at a device, then stream the logs back to your local terminal.
- For production it'd be useful to write logs to a file (or a few files in rotation) that could be grabbed from the file system and viewed for debugging purposes.

## Tasks

- [ ] Propagate task context through log calls (requires #4)
- [ ] Add log handle(s?) to `WasmTask_t` object
- [ ] Create log manager to control log rotation etc.
- [ ] Add logging config to `task` commands
