### ISSUE TITLE
Support Over The Air (OTA) updates

### ISSUE THREAD

**Issue by ryankurte** [ryankurte/rust-esp32-wasm#13]
The base image should have inbuilt (and on by default?) OTA functionality.

## Tasks:

- [ ] Implement OTA manager
  - [ ] Configuration (using config manager)
  - [ ] Command line control
  - [ ] API control
