### ISSUE TITLE
Replace curl with CLI

### ISSUE THREAD

**Issue by ryankurte** [ryankurte/rust-esp32-wasm#3]
As much fun as hand-writing `curl` commands is, a CLI would make this adventure just that much better.
This has been started in https://github.com/ryankurte/rust-esp32-wasm/tree/master/cli

## Tasks:
  - [ ] Read/write files
  - [ ] Read/write keys
  - [ ] Load/unload/start/stop tasks
  - [ ] Fetch/stream application logs (this will require further device support)
