### ISSUE TITLE
Support graceful task shutdown

### ISSUE THREAD

**Issue by ryankurte** [ryankurte/rust-esp32-wasm#6]
The majority of tasks will be long running, as such it is beneficial to provide a mechanism for soft shutdown.

## Tasks:

- [ ] Promotion of task pointer from `WasmArgs` object to `Esp` object (see #4)
- [ ] Addition of a `get_state` function in [wasm.c](https://github.com/ryankurte/rust-esp32-wasm/blob/master/base/main/wasm.c#L61)
- [ ] Addition of a `get_state` call in [runtime.rs](https://github.com/ryankurte/rust-esp32-wasm/blob/master/lib/src/lib.rs)
- [ ] Addition of a safe `get_state` call to the `Esp` object in [lib.rs](https://github.com/ryankurte/rust-esp32-wasm/blob/master/lib/src/lib.rs)
