### ISSUE TITLE
Add mechanism for remote task installation

### ISSUE THREAD

**Issue by ryankurte** [ryankurte/rust-esp32-wasm#7]
Provide a mechanism to download a pre-compiled task blob for use on the device.

## Tasks:
- [ ] Configure CI and upload task objects to a known location
- [ ] Add `FS_MGR_download(char* file_name, char* url)` function to download objects into the file system
  - [ ] Provide console `fs-download FILE_NAME URL` comand
  - [ ] Provide web `/fs/download?file=NAME&url=URL` command (is the URL going to be okay?)
- [ ] Add `APP_MGR_install(char* task_name)` command that fetches task objects from a known source
  - [ ] Provide console `task-install NAME` comand
